<?php
$string['install']="Installation";
$string['lang_select']="Sélectionnez la langue:";
$string['license']="<b>Licence & Conditions</b>";
$string['license_ok']="ACCEPTER";
$string['license_no']="REFUSER";
$string['license_agree']="<b>Continuer si vous acceptez ces termes</b>";
$string['next']="Continuer >>>";
$string['end']=">> Fin <<";
$string['step_1_1']="Création des tables SQL nécessaires à l'utilisation du script.";
$string['step_1_2']="<font color=\"red\">EFFACÉR LES TABLES</font>";
$string['step_1_3']="(<b>toutes les statistiques seront effacés!</b>)";
$string['step_3_1']="Choisir un mot de passe :";
$string['step_3_2']="Retapez le mot de passe :";
//$string['step_4_1']="<b>ATTENTION</b>: Par sécurité, veuillez effacer le fichier <b>setup.php</b> et le Répertoire <b>setup_files</b>.";
$string['step_4_2']="Entrez ce code dans les Pages HTML à surveiller:";
$string['step_4_3']="Entrez ce code dans les Pages PHP à surveiller:<br><font color=\"red\">(pas recommandée, sera supprimé dans les versions futures)</font>";
//$string['step_4_4']="En cas de problèmes utilisez l'option <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">forum de discussion</a>.";
$string['box_title']="Attention:";
$string['done']="Opération réussie.";
$string['permits_0']="PHP Stats a essayé de régler le permis nécessaire,<br>mais certains serveurs ne le permettent pas.<br>Si elle n'a pas été couronnée de succès, vous devrez le faire manuellement.</span><br><br>";
$string['permits_1']="FICHIER OU RÉPERTOIRE";
$string['permits_2']="PERMIS COURANT";
$string['permits_3']="PERMIS REQUIS";
// ERROR HANDLING
$error['error_updating']="<b>ATTENTION: ERREUR CRITIQUE</b><br><br>Il est conseillé de prendre note des erreurs répertoriées ci-dessous et de les ramener sur le forum de support technique.<br><br><b>Le processus d'installation a été arrêté.</b>";
$error['locked']="Php-Stats semble déjà être installé! La procédure d'installation est terminée.<br><br>Si vous souhaitez réinstaller Php-Stats supprimer le fichier <b>php-stats.lock</b> et réinstallez";
$error['error_config']="Php-Stats n\'a pas pu créer le fichier de configuration, le processus d\'installation sera terminée.<br><br>Si vous souhaitez réinstaller Php-Stats supprimer le fichier <b>php-stats.lock</b> et réinstallez";
$error['nowrite_server']="<b>ATTENTION:</b> Vous ne pouvez pas écrire sur votre serveur.<br>Définir les autorisations 777 au Répertoire option<br>autrement, si vous décidez de continuer le scipt sera utilisé sans support en écriture via WEB<br>";
?>
