<?php
$string['install']="Installazione";
$string['lang_select']="Selezionare la ligua:";
$string['license']="<b>Condizioni di licenza</b>";
$string['license_ok']="ACCETTO";
$string['license_no']="NON ACCETTO";
$string['license_agree']="<b>Procedendo accetti tutte queste condizioni di licenza</b>";
$string['next']="Prosegui >>>";
$string['end']=">> Fine <<";
$string['step_1_1']="Verranno ora create le tabelle necessarie all'utilizzo dello script.";
$string['step_1_2']="<font color=\"red\">AZZERA TABELLE</font>";
$string['step_1_3']="(<b>le statistiche verranno cancellate!</b>)";
$string['step_3_1']="Scegliere una password :";
$string['step_3_2']="Reinserire la password :";
//$string['step_4_1']="<b>ATTENZIONE</b>: Ricordarsi di cancellare il file <b>setup.php</b> e la cartella <b>setup_files</b>.";
$string['step_4_2']="Nelle pagine HTML da monitorare inserire il codice:";
$string['step_4_3']="Nelle pagine PHP da monitorare inserire il codice:<br><font color=\"red\">(sconsigliato, sarà rimosso nelle prossime versioni)</font>";
//$string['step_4_4']="In caso di problemi utilizzare l'apposito <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">forum di discussione</a>.";
$string['box_title']="Attenzione:";
$string['done']="Operazione riuscita.";
$string['permits_0']="PHP-Stats ha provato ad impostare i permessi necessari,<br>ma alcuni server non lo consentono.<br>Nel caso non fosse andato a buon fine dovrai farlo manualmente.</span><br><br>";
$string['permits_1']="FILE O DIRECTORY";
$string['permits_2']="PERMESSI ATTUALI";
$string['permits_3']="PERMESSI NECESSARI";
// ERROR HANDLING
$error['error_updating']="<b>ATTENZIONE: ERRORE CRITICO</b><br><br>Si consiglia di prendere nota degli eventuali errori sotto elencati.<br><br><b>La procedura di installazione è stata interrotta.</b>";
$error['locked']="Php-Stats sembra già essere installato e la procedura di installazione verrà terminata.<br><br>Se si vuole reinstallare Php-Stats cancellare prima il file <b>php-stats.lock</b>";
$error['error_config']="Php-Stats non è riuscito a creare il file di config, la procedura di installazione verrà terminata.<br><br>Se si vuole reinstallare Php-Stats cancellare prima il file <b>php-stats.lock</b>";
$error['nowrite_server']="<b>ATTENZIONE:</b> Non è possibile scrivere files sul tuo server.<br>Setta i permessi 777 alla cartella option<br>altrimenti se decidi di continuare verrà usata la modalità senza supporto di scrittura via WEB<br>";
?>
