<?php
$string['install']="Setup";
$string['lang_select']="Please, select your language:";
$string['license']="<b>License Agreement</b>";
$string['license_agree']="<b>By proceed you agree at this License Agreement</b>";
$string['license_ok']="I AGREE";
$string['license_no']="I DON'T AGREE";
$string['next']="Next ->";
$string['end']=">> End <<";
$string['step_1_1']="Now, the necessary tables will be created.";
$string['step_1_2']="<font color=\"red\">RESET TABLES</font>";
$string['step_1_3']="(<b>all data will be deleted!</b>)";
$string['step_3_1']="Insert Password :";
$string['step_3_2']="Re-Type Password :";
//$string['step_4_1']="<b>WARNING</b>: Remember to delete <b>setup.php</b> and related dir <b>setup_files</b>.";
$string['step_4_2']="In your HTML pages you can insert the follow script:";
$string['step_4_3']="In your PHP pages you can insert the follow script:<br><font color=\"red\">(not recommended, will be removed in future versions)</font>";
//$string['step_4_4']="For problems and questions use our <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">discussion board</a>. (italian or english language please)";
$string['box_title']="Warning:";
$string['done']="Successful operation.";
$string['permits_0']='PHP-Stats has tried to set the necessary permits,<br>but some servers do not allow it.<br>If it not successful you will need to do it manually.</span><br><br>';
$string['permits_1']='FILE OR DIRECTORY';
$string['permits_2']='CURRENT PERMITS';
$string['permits_3']='REQUIRED PERMITS';
// ERROR HANDLING
$error['error_updating']="<b>WARNING: CRITICAL ERROR</b><br><br>You can annotate the possible errors.<br><br><b>Setup is halted.</b>";
$error['locked']="Php-Stats seems to be already installed, setup is halted.<br><br>In order to re-install php-stats, please delete file <b>php-stats.lock</b>";
$error['error_config']="Php-Stats can't create config file, setup is halted.<br><br>In order to re-install php-stats, please delete file <b>php-stats.lock</b>";
$error['nowrite_server']="<b>WARNING:</b> It's impossible to write files on your server.<br>Set 777 permits to option folder<br>Otherwise, if you want continue, you will use the no write files on server mode<br>";
?>
